In [1]:
caracter = 'a'
estring = "Hello!"
enter =  123
decimal = 1.23
complexe = 1+23j
logic = False


#Este código no es relevante para nosotros, solamente el resultado
print(type(caracter))
print(type(estring))
print(type(enter))
print(type(decimal))
print(type(complexe))
print(type(logic))

<class 'str'>
<class 'str'>
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>


In [2]:
!uv pip freeze

anyio==4.11.0
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
arrow==1.4.0
asttokens==3.0.0
async-lru==2.0.5
attrs==25.4.0
babel==2.17.0
beautifulsoup4==4.14.2
bleach==6.2.0
certifi==2025.10.5
cffi==2.0.0
charset-normalizer==3.4.4
colorama==0.4.6
comm==0.2.3
contourpy==1.3.3
cycler==0.12.1
debugpy==1.8.17
decorator==5.2.1
defusedxml==0.7.1
executing==2.2.1
fastjsonschema==2.21.2
fonttools==4.60.1
fqdn==1.5.1
h11==0.16.0
httpcore==1.0.9
httpx==0.28.1
idna==3.11
ipykernel==7.0.1
ipython==9.6.0
ipython-pygments-lexers==1.1.1
ipywidgets==8.1.7
isoduration==20.11.0
jedi==0.19.2
jinja2==3.1.6
json5==0.12.1
jsonpointer==3.0.0
jsonschema==4.25.1
jsonschema-specifications==2025.9.1
jupyter==1.1.1
jupyter-client==8.6.3
jupyter-console==6.6.3
jupyter-core==5.9.1
jupyter-events==0.12.0
jupyter-lsp==2.3.0
jupyter-server==2.17.0
jupyter-server-terminals==0.5.3
jupyterlab==4.4.9
jupyterlab-pygments==0.3.0
jupyterlab-server==2.27.3
jupyterlab-widgets==3.0.15
kiwisolver==1.4.9
lark==1.3.0
markupsafe==

In [3]:
import numpy as np

In [3]:
x = 10.0
y = 5
resultado = x + y
print(resultado)

15.0


In [4]:
a = 10
b = 20
x = 45
r = (a + b - 5) + (x + 10 + 20)
print(r)

100


In [5]:
division_decimal = 3 / 2
print(division_decimal)

1.5


In [ ]:
division_entera = 3 // 2
division_entera

In [6]:
x = 5.3
y = 5.5
comparacion_1 = x < y
comparacion_1

True

In [7]:
letra_a = 'a'
letra_b = 'b'

comparacion_2 = letra_a != letra_b
comparacion_2

True

In [8]:
letra_a = 'a'
letra_b = 'b'

comparacion_3 = letra_a > letra_b
comparacion_3

False

In [9]:
verdadero = True
falso = False

In [10]:
operador_not = not verdadero
operador_not

False

In [11]:
operador_or = verdadero or falso
operador_or

True

In [12]:
operador_or = falso or falso
operador_or

False

In [18]:
operador_and = verdadero and falso
operador_and

False

In [14]:
operador_and = verdadero and verdadero
operador_and

True

In [19]:
x = 4
y = 5

x += y
print(x)

9


In [20]:
x = 4
y = 5
x = x + y
print(x)

9


In [21]:
print("Hola mon!")

print("Esto es un texto" + " el cual concatenam con otro texto")

a = 'a' + " " + 'b'

print("También lo podemos hacer así " + a)

num = 3
print(f'Texto concatenado con un número "{num}"')

Hola mon!
Esto es un texto el cual concatenam con otro texto
También lo podemos hacer así a b
Texto concatenado con un número "3"


In [26]:
def m_a_cm(metros):
    centimetros = metros * 100
    return centimetros

print(m_a_cm(100))


10000


33 metros son 3300 cm


In [32]:
# La variable transformado recoge el valor de la función m_a_cm
# podemos usar este valor para otras tareas en nuestro programa
m = 33
transformado = m_a_cm(m)

print(f'{m} metros son {transformado} cm')

33 metros son 3300 cm


In [41]:
def IMC(peso, altura):
    imc= (peso/(altura*100)**2)
    return imc

In [42]:
peso=60
altura=2
resultado= IMC(peso, altura)
print(resultado)

0.0015


In [44]:
a = 5
b = 10

# Verificamos que 'a' no sea 0 (si lo fuera, no sería una ecuación de primer grado)
if a != 0:
    x = -b / a
    print(f"La ecuación es: {a}x + {b} = 0")
    print(f"La solución es: x = {x}")
else:
    print("No es una ecuación de primer grado (a no puede ser 0).")

La ecuación es: 5x + 10 = 0
La solución es: x = -2.0


In [45]:
def es_bisiesto(anio):
    """Devuelve True si el año es bisiesto, False en caso contrario."""
    if (anio % 4 == 0 and anio % 100 != 0) or (anio % 400 == 0):
        return True
    else:
        return False

# Comprobación de la función
anios_prueba = [2024, 2023, 1900, 2000, 2100]

for anio in anios_prueba:
    print(f"{anio}: {'Bisiesto' if es_bisiesto(anio) else 'No bisiesto'}")

2024: Bisiesto
2023: No bisiesto
1900: No bisiesto
2000: Bisiesto
2100: No bisiesto


In [46]:
import math

def ecuacion_segundo_grado(a, b, c):
    """Devuelve las soluciones reales o complejas de ax² + bx + c = 0."""
    discriminante = b**2 - 4*a*c

    if a == 0:
        raise ValueError("No es una ecuación de segundo grado (a no puede ser 0).")

    if discriminante > 0:
        x1 = (-b + math.sqrt(discriminante)) / (2 * a)
        x2 = (-b - math.sqrt(discriminante)) / (2 * a)
        return x1, x2
    elif discriminante == 0:
        x = -b / (2 * a)
        return x,
    else:
        # Soluciones complejas
        parte_real = -b / (2 * a)
        parte_imaginaria = math.sqrt(-discriminante) / (2 * a)
        x1 = complex(parte_real, parte_imaginaria)
        x2 = complex(parte_real, -parte_imaginaria)
        return x1, x2

# 🔍 Ejemplo de comprobación
a, b, c = 1, 10, 1  # ecuación: x² + 10x + 1 = 0
soluciones = ecuacion_segundo_grado(a, b, c)
print("Soluciones:", soluciones)

Soluciones: (-0.10102051443364424, -9.898979485566356)


In [47]:
# Programa que calcula el valor absoluto de un numero
x = 12

#Bloque condicional
if x < 0:
    print("Entramos en el bloque condicional")
    x = x * -1  # x*= -1 o també x = -x

print("Estamos fuera del bloque condicional")
# Resultados
print(f'El valor absoluto es: {x}')

Estamos fuera del bloque condicional
El valor absoluto es: 12


In [50]:
x = -1

if x > 0:
    print("Evaluamos el número")  # Un bloque con dos sentencias de código
    print("El número es positivo")
else:
    print("El número es negativo")

El número es negativo


In [51]:
x = 0

if x > 0:
     print("Evaluamos el número") # Un blog con dos sentencias de código.
     print("El número es positivo")

elif x == 0: # Aquí contemplamos que el número pueda ser 0

     print("El número es cero")

else:
# Aquí no necesitamos una nueva condición, si el número no es positivo
# ni cero, seguro que es negativo

     print("El número es negativo")

print("Hasta la próxima vez")

El número es cero
Hasta la próxima vez


In [56]:
n = 5
print("El valor inicial de la variable 'n' es: " + str(5))
while n > 0: # Que pasa cuando n = 0 ?

    print(n)
    n = n - 1

print(f'Valor de n = {n}')
print("Out!")

El valor inicial de la variable 'n' es: 5
5
4
3
2
1
Valor de n = 0
Out!


In [57]:
for i in (0,1,2,3,4,5):
    s = i + 3
    print(s)

3
4
5
6
7
8


In [58]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [61]:
for i in range(7):
    print(i)


0
1
2
3
4
5
6


In [63]:
for i in (0,1,2,4,5):
    print(i)

0
1
2
4
5


In [65]:
for i in range(7):
    if i == 3 or i == 6:
        continue  # Salta el 3 y el 6
    print(i)


0
1
2
4
5


In [67]:
n = int(input("3"))
print(f"Los divisores de {n} son:")
for i in range(1, n + 1):
    if n % i == 0:
        print(i)
    

3 5


Los divisores de 5 son:
1
5


In [69]:
def hora_valida(horas, minutos, segundos):
    if 0 <= horas <= 23 and 0 <= minutos <= 59 and 0 <= segundos <= 59:
        print("La hora es válida.")
    else:
        print("La hora NO es válida.")

hora_valida(12, 45, 30)  # ✅ válida
hora_valida(25, 10, 0)   # ❌ no válida

La hora es válida.
La hora NO es válida.


In [70]:
n = int(input("Ingresa un número entero: "))

# Calcular la suma de los divisores propios
suma_divisores = 0
for i in range(1, n):
    if n % i == 0:
        suma_divisores += i

# Clasificar el número
if suma_divisores == n:
    print(f"{n} es un número PERFECTO.")
elif suma_divisores < n:
    print(f"{n} es un número DEFICIENTE.")
else:
    print(f"{n} es un número ABUNDANTE.")

Ingresa un número entero:  5


5 es un número DEFICIENTE.


In [71]:
for i in range(1, 6):
    print("1 " * i)

# Parte inferior del patrón
for i in range(4, 0, -1):
    print("1 " * i)


1 
1 1 
1 1 1 
1 1 1 1 
1 1 1 1 1 
1 1 1 1 
1 1 1 
1 1 
1 


In [72]:
llista = ["foo", "bar", "baz", "qux", "quux", "corge"]

print(llista)

['foo', 'bar', 'baz', 'qux', 'quux', 'corge']


In [73]:
ll = list()

In [74]:
lista2 = []

In [75]:
a = [0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
    20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
    60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
    80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

print(f'La llista a es: {a}')

La llista a es: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [3]:
ll = ["foo", "bar", "baz", "qux", "quux", "corge"]

# Ahora intentaremos obtener la información guardada en una posición de la lista

primera = ll[0]
print(primera)

tercera = ll[2]
print(tercera)

foo
baz


In [77]:
ll[-1] # indexa el último elemento de la lista.

'corge'

In [4]:
print("Lista entera:", end=" ")
print(ll)
print("Mi sub-lista:", end=" ")

sublista = ll[1:3]
print(sublista)

Lista entera: ['foo', 'bar', 'baz', 'qux', 'quux', 'corge']
Mi sub-lista: ['bar', 'baz']


In [10]:
#SLICING

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(lista[:5]) # Seleccionamos del primero hasta al 5o elemento
print(lista[5:]) # Seleccionamos del 5o elemento hasta al 5o final

# Se puede especificar cómo es el incremento de los índices
print(lista[1::3])

print("Soluciones")
# ¿Qué que puede dar ll[:]?
print(lista[:])

# ¿Cómo conseguiremos los elementos pares de la lista?
pares = lista[1::2]
print("Pares: " + str(pares))

# ¿Y los impares del 3 al 9?
senars_3_9 = lista[::2]
print(f'Impares del 3 al 9: {senars_3_9}')

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[2, 5, 8]
Soluciones
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Pares: [2, 4, 6, 8, 10]
Impares del 3 al 9: [1, 3, 5, 7, 9]


In [8]:
#cambiar un valor de una lista: 
ll = [1, 2, 3, 4, 5]

print(f'Lista original " {ll}')
ll[0] = -33

print(f'Lista modificada en la primera posicion {ll}')

ll[-1] = 55
print(ll)

Lista original " [1, 2, 3, 4, 5]
Lista modificada en la primera posicion [-33, 2, 3, 4, 5]
[-33, 2, 3, 4, 55]


In [12]:
#asignarle múltiples elementos en una sola asignación usando listas del mismo tamaño
ll[0:2] = [33, 33]
print(ll)

[33, 33, 3, 4, 55]


In [15]:
#METODOS PAR MODIFICAR UNA LISTA:
a = [1, 2]
a.append(3)
print(a)

a.append(5)
a.extend([5, 6])
print(a)

# Del resultat de la operació extend, veiem que no tenim el nombre 4.
# usam la métode insert per afegir-ho
a.insert(3, 4)
print(a)

a.remove(1)
print(a)

# Observad que pasaría si tengo esta lista
b = [1,2,2,3,4,5,6,7]
b.remove(2)
print(b)

# Volvemos a nuestra lista en, vamos a usar el método pop
a.pop(0)
print(a)
a.pop()
print(a)

[1, 2, 3]
[1, 2, 3, 5, 5, 6]
[1, 2, 3, 4, 5, 5, 6]
[2, 3, 4, 5, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[3, 4, 5, 5, 6]
[3, 4, 5, 5]


In [20]:
#OPERADORES IN NOT
separadores = [' ', ',', ';', '-']
x = ',' in separadores
print(x)
x = 'j' not in separadores
print(x)

#CONCATENACION Y MULTIPLICACION: 
lista_a = [1, 2, 3]
lista_b = [4, 5, 6]
lista_c = [0] * 10
print(lista_c)
print(lista_a + lista_b)

#LEN, MINIMO Y MAXIMO
coleccion = [1,2,3,9,5,6]

longitud = len(coleccion)
print(longitud)
valor_maximo = max(coleccion)
print(valor_maximo)

True
True
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 2, 3, 4, 5, 6]
6
9


In [21]:
#LISTAS CON PARAMETROS DE SUBPROGRAMAS

"Función que recibe una lista y un elemento y añade el elemento al final de la lista"
def anyadir(lista, element):

    lista.append(element)

ll_mutable = []

print("Lista antes de llamar al método añade_elemento: ", ll_mutable)
anyadir(ll_mutable, 5)
print("Lista después de llamar al método añade_elemento:", ll_mutable)

Lista antes de llamar al método añade_elemento:  []
Lista después de llamar al método añade_elemento: [5]


In [23]:
#ITERANDO SOBRE LISTAS:

# Recorrer una lista obteniendo cada uno de sus elementos
llista_pobles = ["Arta", "Sineu", "Alcudia", "Mancor", "Valldemossa"]

for poble in llista_pobles: # el operador for nos devuelve cada uno de los elementos de la lista
    print(poble)
#Recorrer una lista con los índices para modificar valores
notas = [9, 4.5, 3.0, 7, 6.5, 3]
longitud = len(notas)

for i in range(0, longitud): # recuerde que la función range nos crea una lista
    print(i, notas[i])
    notas[i] = notas[i] + 1

print(notas)

for  idx, item in enumerate(notas): # mentre no final
    print(f'indice {idx} , item {item}')    

Arta
Sineu
Alcudia
Mancor
Valldemossa
0 9
1 4.5
2 3.0
3 7
4 6.5
5 3
[10, 5.5, 4.0, 8, 7.5, 4]
indice 0 , item 10
indice 1 , item 5.5
indice 2 , item 4.0
indice 3 , item 8
indice 4 , item 7.5
indice 5 , item 4


In [1]:
# archivo ejemplo.py
def saludar(nombre):
    return f"Hola, {nombre}!"

if __name__ == "__main__":
    nombre = input("Ingresa tu nombre: ")
    print(saludar(nombre))

Ingresa tu nombre:  Laura


Hola, Laura!


In [ ]:
#NUMPY

In [4]:
#COMPROBAR SI ESTA INSTALADA
!uv pip freeze | findstr numpy

numpy==2.3.4


In [5]:
import numpy as np

data = np.array([1,0])
print(data[0])
print(type(data[0]))

data = np.array([[1,0],[2,0],[3,0]])
print(data[0][:0])

1
<class 'numpy.int64'>
[]


In [6]:
print(data.shape)
print(data.size)
print(data.ndim)
print(data.dtype)

(3, 2)
6
2
int64


In [7]:
# VER LO DE DTYPE!!!
data = np.array([[1,0],[2,0]],dtype=np.int32)
data = np.array([[1,0],[2,0]],dtype=np.complex64)
data = np.array([[1,0],[2,0]],dtype=np.float16)
# Conversión
data = np.array(data,dtype=np.uint)
data = data.astype(np.bool_)
print(data)

[[ True False]
 [ True False]]


In [8]:
#COMO GENERAR VALORES
data = np.array(range(10))
print(data)

data = np.arange(10)
print(data)

data = np.zeros((10,5))
# https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
print(data)

data = np.ones(10) #crea un array de 10 dimensiones
print(data)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
shape = (10,80) # 10 rows x 80 cols
data = np.zeros(shape)
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0.

In [5]:
data = np.linspace(3,4,100)
print(data)

[3.         3.01010101 3.02020202 3.03030303 3.04040404 3.05050505
 3.06060606 3.07070707 3.08080808 3.09090909 3.1010101  3.11111111
 3.12121212 3.13131313 3.14141414 3.15151515 3.16161616 3.17171717
 3.18181818 3.19191919 3.2020202  3.21212121 3.22222222 3.23232323
 3.24242424 3.25252525 3.26262626 3.27272727 3.28282828 3.29292929
 3.3030303  3.31313131 3.32323232 3.33333333 3.34343434 3.35353535
 3.36363636 3.37373737 3.38383838 3.39393939 3.4040404  3.41414141
 3.42424242 3.43434343 3.44444444 3.45454545 3.46464646 3.47474747
 3.48484848 3.49494949 3.50505051 3.51515152 3.52525253 3.53535354
 3.54545455 3.55555556 3.56565657 3.57575758 3.58585859 3.5959596
 3.60606061 3.61616162 3.62626263 3.63636364 3.64646465 3.65656566
 3.66666667 3.67676768 3.68686869 3.6969697  3.70707071 3.71717172
 3.72727273 3.73737374 3.74747475 3.75757576 3.76767677 3.77777778
 3.78787879 3.7979798  3.80808081 3.81818182 3.82828283 3.83838384
 3.84848485 3.85858586 3.86868687 3.87878788 3.88888889 3.89898

In [11]:
#EMPEZA EN 10**0 Y TERMINA EN 10**2 Y CREA UNA SECUENCIA DE 10 PUNTOS
data = np.logspace(0,2,10) # 10puntos entre 2**0 y 2**2
print(data)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [12]:
#MATRIZ DE IDENTIDAD
data = np.identity(3)
print(data)
print("-"*10) #LE DICE REPITE - 10 VECES PARA QUE QUEDEN SEPARADOS LOS RESULTADOS

data = np.eye(3,k=1) # https://numpy.org/doc/stable/reference/generated/numpy.eye.html
print(data)
print("-"*10)

data = np.diag(range(1,4))
print(data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
----------
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
data = np.random.rand(3,3)
print(data)
print("-"*20)

data = np.random.randint(1,10,size=(2,2)) #GENERA NUMEROS ENTEROS ALEATORIOS. AQUI LE DIGO, GENERAME UNA MATRIZ DE DOS FILAS POR DOS COLUMNAS DE NUEMEROS ENTEROS ALEATRORIOS QUE VAYAN DEL 1 AL 10
print(data)
print("-"*20)

data = np.random.randint(1,10,20).reshape(10,2)
print(data)
print("-"*20)

data = np.array(np.random.rand(20)*10,dtype=int).reshape(10,2)
print(data)

[[0.2280432  0.70959394 0.92342651]
 [0.84327131 0.28566117 0.35004573]
 [0.8202077  0.03221232 0.85812535]]
--------------------
[[1 1]
 [5 7]]
--------------------
[[4 2]
 [7 5]
 [6 6]
 [2 3]
 [6 7]
 [3 3]
 [8 8]
 [7 2]
 [3 8]
 [1 4]]
--------------------
[[6 9]
 [2 1]
 [7 2]
 [3 9]
 [7 2]
 [4 1]
 [8 5]
 [3 0]
 [7 0]
 [2 5]]


In [ ]:
array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
data = np.arange(10)

data1 = np.tile(data,(10,1)) #crea una matriz de la dimension de shape toda de 1 que se multiplique por la matriz data
print(data1)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [ ]:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [57]:
a= (1,2,3)
b=np.tile (a,3)
print(b)
c=np.repeat(a,3)
print(c)
resultado=np.concatenate((c,b))
print(resultado)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [60]:
np.concatenate((np.repeat([1,2,3],3),np.tile([1,2,3],3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [68]:
import numpy as np
a = np.array([.0,0.1])
b = np.array([1,1])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(2**a)

[1.  1.1]
[-1.  -0.9]
[0.  0.1]
[0.  0.1]
[1.         1.07177346]


In [77]:
np.random.seed(2022)
a = np.random.randint(-90,0,4)
print(a)
index = np.where(a<-80) # Alerta: Son índices
print(index)
print(a[index])
print(np.logical_or(a<-80,a<-90))
print(np.logical_not(np.logical_or(a<-40,a<-90)))

[-45 -41 -35  -2]
(array([], dtype=int64),)
[]
[False False False False]
[False False  True  True]


In [14]:
a = np.array([.0,0.1])
b = np.array([1,1])
c = np.array([1,1,1])
c = np.array([1,1,1,1]).reshape(2,2)
print(a*c)
print("-"*10)
print(a.dot(c)) 

[[0.  0.1]
 [0.  0.1]]
----------
[0.1 0.1]


In [16]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print(a)
print(b)
print(c)
print(c.shape)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]]
[[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]
(5, 2)


In [17]:
a = np.arange(1,5).reshape(2,2)
print(a)
b = np.array([0,5,6,7]).reshape(2,2)
print(b)
print("-"*10)
k = np.kron(a,b)
print(k)

[[1 2]
 [3 4]]
[[0 5]
 [6 7]]
----------
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [18]:
print(a)
print(np.ravel(a))

print(np.ravel(a,order="F")) # ‘F’ means to index the elements in column-major,

[[1 2]
 [3 4]]
[1 2 3 4]
[1 3 2 4]


In [9]:
a = np.array(range(10))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))
print ("-"*10)
print(np.sum(a))
print(np.cumsum(a))
print(np.mean(a))

print("\n",np.cumprod(a))
print(np.min(a))
print(np.argmax(a))

print(a.mean())
print(a.min())
print(a.argmax())

a = a.reshape(2,5)
print(a)
print("-"*10)
print(np.sum(a,axis=1)) #suma de filas
print(np.sum(a,axis=0)) #suma de columas

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
----------
45
[ 0  1  3  6 10 15 21 28 36 45]
4.5

 [0 0 0 0 0 0 0 0 0 0]
0
9
4.5
0
9
[[0 1 2 3 4]
 [5 6 7 8 9]]
----------
[10 35]
[ 5  7  9 11 13]


C:\Users\Nico\AppData\Local\Temp\ipykernel_14200\1542189012.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [10]:

a = np.arange(10)
print(a.shape)
print(a.reshape(2,5))
print(a)

(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
a = a.reshape(2,5)
print(a.T)
print("-"*10)
print(np.hstack(a))  

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
----------
[0 1 2 3 4 5 6 7 8 9]


In [12]:
b = np.arange(10,20).reshape(2,5)
print(b)
print("-"*10)
print(np.hstack((a,b))) # axis-1
print(np.vstack((a,b))) # axis-0

[[10 11 12 13 14]
 [15 16 17 18 19]]
----------
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
c = np.dstack((a,b)) # axis-2  https://numpy.org/doc/stable/reference/generated/numpy.dstack.html
print(c)
print(c.shape)

[[[ 0 10]
  [ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]]]
(2, 5, 2)


In [80]:
a = np.arange(10)
b = np.arange(5,15)
print(a)
print(b)
print("-"*10)
print(np.isin(a,b))
print(np.intersect1d(a,b))
print("-"*10)
print(np.setdiff1d(a,b))
print(np.setdiff1d(b,a))
print("-"*10)
print(np.union1d(a,b))

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
----------
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]
----------
[0 1 2 3 4]
[10 11 12 13 14]
----------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [81]:
a = np.arange(10)
print(a.shape)
print(a.reshape(2,5))
print(a)

a = a.reshape(2,5)
print(a.T)
print("-"*10)
print(np.hstack(a))  # https://numpy.org/doc/stable/reference/generated/numpy.hstack.html

b = np.arange(10,20).reshape(2,5)
print(b)
print("-"*10)
print(np.hstack((a,b))) # axis-1
print(np.vstack((a,b))) # axis-0

c = np.dstack((a,b)) # axis-2  https://numpy.org/doc/stable/reference/generated/numpy.dstack.html
print(c)
print(c.shape)
print(a)
print(np.ravel(a)) # https://numpy.org/doc/stable/reference/generated/numpy.ravel.html

print(np.ravel(a,order="F")) # ‘F’ means to index the elements in column-major,
print(a)
print(np.split(a,2))
c1,c2 = np.split(a,2)

print("-"*10)

print(c1)
print(c1.shape)
print(np.ravel(c1))
print(c2)
print(np.concatenate((a,b)))
print("-"*10)
print(np.concatenate((a,b),axis=1))
# https://pillow.readthedocs.io/en/stable/

(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
----------
[0 1 2 3 4 5 6 7 8 9]
[[10 11 12 13 14]
 [15 16 17 18 19]]
----------
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0 10]
  [ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]

 [[ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]]]
(2, 5, 2)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 5 1 6 2 7 3 8 4 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
----------
[[0 1 2 3 4]]
(1, 5)
[0 1 2 3 4]
[[5 6 7 8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
----------
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]
