In [9]:
import numpy as np

In [ ]:
#Ejercicio 1
a = np.array(range(20))
print(a)
print("-"*10)
b = np.linspace(0,1,10)
print(b)
print("-"*10)
data= np.array([5,5,5])
c = np.tile(data,(3,1))
print(c)

In [32]:
#Ejercicio 2
x = np.arange(10, 30)
print(x)
print("-"*10)
print(x[3:8])
print("-"*10)
pares = x[::2]
print("Pares: " + str(pares))
print("-"*10)
x[-1] = 100
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
----------
[13 14 15 16 17]
----------
Pares: [10 12 14 16 18 20 22 24 26 28]
----------
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28 100]


In [35]:
#Ejercicio 3
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a+b)
print("-"*10)
print(a*b)
print("-"*10)
print(b/a)
print("-"*10)
a_cuadrado = a ** 2
print(a_cuadrado)

[11 22 33 44 55]
----------
[ 10  40  90 160 250]
----------
[10. 10. 10. 10. 10.]
----------
[ 1  4  9 16 25]


In [41]:
#Ejercicio 4
arr = np.random.randint(1, 101, size=20)
print(arr)
print("-"*10)
media= np.mean(arr)
print(media)
print("-"*10)
desviacion_estandar = np.std(arr)
print(desviacion_estandar)
print("-"*10)
valor_maximo = max(arr)
print(valor_maximo)
posicion_maximo = np.argmax(arr)
print(posicion_maximo)


[77  7 51 10 78 47 63 11 37 17 26 28  9  8 74 55 20 99 44 13]
----------
38.7
----------
27.548321182968664
----------
99
17


In [101]:
#Ejercicio 5
data = np.random.randint(1,16,size=(4,4)) 
print(data)
print("-"*20)
print(data[0])
print(data[:,-1])
print("-"*20)
submatriz = data[1:3, 1:3]
print(submatriz)
print("-"*20)
suma_filas = np.sum(data, axis=1)
print(suma_filas)
print("-"*20)
suma_columnas = np.sum(data, axis=0)
print(suma_columnas)

[[ 4 14 11  6]
 [ 8 13  2  1]
 [ 8  2  8  6]
 [ 9  1  8  2]]
--------------------
[ 4 14 11  6]
[6 1 6 2]
--------------------
[[13  2]
 [ 2  8]]
--------------------
[35 24 24 20]
--------------------
[29 30 29 15]


In [4]:
#Ejercicio 6
temps = np.array([18, 20, 22, 21, 19, 17, 16]) #Temperaturas diarias de una ciudad en una semana
media= np.mean(temps)
print(media)
print("-"*10)
supero_media = temps > media
print(supero_media)
supero_media_dia=np.where(temps > media)
print(supero_media_dia)
print("-"*10)
fahrenheit = temps * (9/5)+32
print(fahrenheit)
print("-"*10)
dia_8=np.append (temps, 23)
print(dia_8)

19.0
----------
[False  True  True  True False False False]
(array([1, 2, 3]),)
----------
[64.4 68.  71.6 69.8 66.2 62.6 60.8]
----------
[18 20 22 21 19 17 16 23]


In [11]:
#Ejercicio 7
data_1= np.loadtxt( "datos_1 (1).csv", delimiter= ",")
data_1

array([[ 42.,  16.,   8.,  95.,  59.,  57.,  91.,  75.,   5.,  45.],
       [ 52.,  14.,  90.,   2.,   7.,  79.,  57.,   1.,  43.,  27.],
       [ 36.,  31.,  46.,  79.,  25.,  61., 100.,  63.,  36.,  24.],
       [ 83.,  59.,  33.,  95.,  94.,  76.,  91.,  33.,  55.,  62.],
       [ 60.,  90.,  67.,  66.,  34.,  71.,  93.,  20.,  77.,  51.],
       [ 24.,  62.,  72.,  17.,  78.,  93.,  52.,  24.,  86.,  10.]])

In [12]:
data_2= np.loadtxt( "datos_2 (1).csv", delimiter= ",")
data_2

array([[ 38.,   5.,   6.,  57.,  67.,  52.,  77.,  99.,  80.,  74.],
       [ 49.,  44.,  20.,  97.,   3.,  82.,  46.,  81., 100.,  47.],
       [ 83.,  59.,  33.,  95.,  94.,  76.,  91.,  33.,  55.,  62.],
       [ 34.,  25.,  85.,  61.,  65.,  73.,  59.,  22.,  45.,  90.],
       [ 14.,  60.,  46.,  85.,  52.,  93.,  38.,  89.,  79.,  10.],
       [ 42.,  16.,   8.,  95.,  59.,  57.,  91.,  75.,   5.,  45.]])

In [137]:
#Apartado a
media_data_1= np.mean(data_1)
print(f'La media de data_1 es: {media_data_1}')
mediana_data_1 = np.median(data_1)
print(f'La mediana de data_1 es: {mediana_data_1}')
minimo_data_1= np.min(data_1)
print(f'El minimo de data_1 es: {minimo_data_1}')
maximo_data_1= np.max(data_1)
print(f'El maximo de data_1 es: {maximo_data_1}')
longitud_data_1= np.size(data_1)
print(f'La cantidad de elementos de data_1 es: {longitud_data_1}')
print("-"*10)
media_data_2= np.mean(data_2)
print(f'La media de data_2 es: {media_data_2}')
mediana_data_2 = np.median(data_2)
print(f'La mediana de data_2 es: {mediana_data_2}')
minimo_data_2= np.min(data_2)
print(f'El minimo de data_2 es: {minimo_data_2}')
maximo_data_2= np.max(data_2)
print(f'El maximo de data_2 es: {maximo_data_2}')
longitud_data_2= np.size(data_2)
print(f'La cantidad de elementos de data_2 es: {longitud_data_2}')

La media de data_1 es: 53.233333333333334
La mediana de data_1 es: 57.0
El minimo de data_1 es: 1.0
El maximo de data_1 es: 100.0
La cantidad de elementos de data_1 es: 60
----------
La media de data_2 es: 57.05
La mediana de data_2 es: 59.0
El minimo de data_2 es: 3.0
El maximo de data_2 es: 100.0
La cantidad de elementos de data_2 es: 60


In [23]:
#Apartado b,
interseccion= np.intersect1d(data_1[0, :], data_2[0, :])
print(interseccion)
print("-"*10)
union= np.union1d(data_1[0:2, :], data_2[0:2, :])
print(union)
print("-"*10)

unique_data_1_data_2, freqdata_1_data_2= np.unique( data_1_data_2, axis=0, return_counts= True)
print(unique_data_1_data_2, freqdata_1_data_2)
print("-"*3)
filas_repetidas= unique_data_1_data_2 [freqdata_1_data_2 > 1]
print(filas_repetidas)

[ 5. 57.]
----------
[  1.   2.   3.   5.   6.   7.   8.  14.  16.  20.  27.  38.  42.  43.
  44.  45.  46.  47.  49.  52.  57.  59.  67.  74.  75.  77.  79.  80.
  81.  82.  90.  91.  95.  97.  99. 100.]
----------
[[ 14.  60.  46.  85.  52.  93.  38.  89.  79.  10.]
 [ 24.  62.  72.  17.  78.  93.  52.  24.  86.  10.]
 [ 34.  25.  85.  61.  65.  73.  59.  22.  45.  90.]
 [ 36.  31.  46.  79.  25.  61. 100.  63.  36.  24.]
 [ 38.   5.   6.  57.  67.  52.  77.  99.  80.  74.]
 [ 42.  16.   8.  95.  59.  57.  91.  75.   5.  45.]
 [ 49.  44.  20.  97.   3.  82.  46.  81. 100.  47.]
 [ 52.  14.  90.   2.   7.  79.  57.   1.  43.  27.]
 [ 60.  90.  67.  66.  34.  71.  93.  20.  77.  51.]
 [ 83.  59.  33.  95.  94.  76.  91.  33.  55.  62.]] [1 1 1 1 1 2 1 1 1 2]
---
[[42. 16.  8. 95. 59. 57. 91. 75.  5. 45.]
 [83. 59. 33. 95. 94. 76. 91. 33. 55. 62.]]
