In [4]:
import numpy as np

data = np.array([1,0])
print(data[0])
print(type(data[0]))

data = np.array([[1,0],[2,0],[3,0]])
print(data[0][:0])

1
<class 'numpy.int64'>
[]


In [2]:
import numpy as np

data = np.array([1,0])
print(data[0])
print(type(data[0]))

data = np.array([[1,0],[2,0],[3,0]])
print(data[0][:0])

1
<class 'numpy.int64'>
[]


In [3]:
import numpy as np

data = np.array([1,0])
print(data[0])
print(type(data[0]))

data = np.array([[1,0],[2,0],[3,0]])
print(data[0][:0])

1
<class 'numpy.int64'>
[]


In [4]:
print(data.shape)
print(data.size)
print(data.ndim)
print(data.dtype)


(3, 2)
6
2
int64


In [6]:
data = np.array([[1,0],[2,0]],dtype=np.int32)
data = np.array([[1,0],[2,0]],dtype=np.complex64)
data = np.array([[1,0],[2,0]],dtype=np.float16)
# Conversión
data = np.array(data,dtype=np.uint)
data = data.astype(np.bool_)
print(data)

[[ True False]
 [ True False]]


In [7]:
data = np.array(range(10))
print(data)

data = np.arange(10)
print(data)

data = np.zeros((10,5))
# https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
print(data)

data = np.ones(10)
print(data)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
shape = (10,80) # 10 rows x 80 cols
data = np.zeros(shape)
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0.

In [9]:
data = np.linspace(0,1,10)
print(data)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
data = np.logspace(0,2,10) # 10puntos entre 2**0 y 2**2
print(data)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [12]:
data = np.identity(3)
print(data)
print("-"*10)

data = np.eye(3,k=1) # https://numpy.org/doc/stable/reference/generated/numpy.eye.html
print(data)
print("-"*10)

data = np.diag(range(1,4))
print(data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
----------
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [41]:
data =np.array(range(1,4))
repeated_data = np.repeat(data, 3)
resultado = np.concatenate((repeated_data, data))
print(resultado)

[1 1 1 2 2 2 3 3 3 1 2 3]


In [42]:
np.repeat (np.array(range(1,4)),3,0)



array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [5]:
np.concatenate((np.repeat([1,2,3],3),np.tile([1,2,3],3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
sumatoria-> np.sum(data)
a^b-> a**b
raiz cuadradada-> np.sqrt(data)

In [ ]:
np.sqrt(np.sum(x1-x2)**2
        

In [55]:
v1 = np.arange(1,4)
v2 = np.arange(4,7)


In [56]:
v1, v2

(array([1, 2, 3]), array([4, 5, 6]))

In [25]:
!uv pip install pillow

Audited 1 package in 17ms


In [ ]:
from PIL import Image

image = Image.open('images/gatito.jpeg')
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)

display(image)
#PUEDO IMPORTAR UNA IMAGEN DE DONDE LA USO, SI ESTA EN UNA SUBCARPETA LO AGREGO LO QUE LE INDICO ES UN ARRAY NUMPY QUE IMPRIMA LAS DIMENSIONES DE LA IMAGEN (w,h,1)

In [ ]:
data = np.asarray(image)
print(len(data[0]))
print(data.size)
print(data.shape)
w,h,_ = data.shape

In [ ]:
print(data[w//2,h//2])
data2 = data.copy()
data2[w//2,h//2] = np.array([255,0,0]) # a red point

img = Image.fromarray(data2, 'RGB')

display(img)
# // DIVIDE Y SOLO DEJA LA PARTE ENTERA

In [ ]:
center_mask = w//2,h//2
rectangle_size = int(w*0.1)
mask = np.ones(rectangle_size*rectangle_size).reshape(rectangle_size,rectangle_size)
print(mask.shape)

for x in range(w//2,w//2+rectangle_size):
    for y in range(h//2,h//2+rectangle_size):
        data2[x,y] =  np.array([255,0,0])


img = Image.fromarray(data2, 'RGB')
display(img)

# REALMENTE, el cuadrado está en el centro?, ESO PORQUE HAY QUE INDICARLE  + /- ZONA 


In [33]:
! uv pip install numpy

Audited 1 package in 38ms


In [34]:
! uv pip install pillow

Audited 1 package in 12ms


In [35]:
from PIL import Images

image = Image.open('gato.jpg')
print(image.format)
print(image.size)
print(image.mode)

display(image)

ImportError: cannot import name 'Images' from 'PIL' (C:\Users\Nico\ttda\.venv\Lib\site-packages\PIL\__init__.py)

In [19]:
data = np.asarray(images)
print(len(data[0]))
print(data.size)
print(data.shape)
w,h,_ = data.shape

NameError: name 'images' is not defined

In [9]:
data = np.asarray(images)
data2 = data.copy()
for x in range(data2.shape[0]): #no eficiente
     for y in range(data2.shape[1]):
         data2[x,y] = np.repeat(data[x,y].mean(),3)

img = Image.fromarray(data2, 'RGB')
display(img)

NameError: name 'images' is not defined

In [ ]:
base=array [(0,1,2,3,4,5,6,7,8,9)]
def par 