In [1]:
import numpy as np


In [2]:
np.random.seed(2022)
a = np.random.randint(-30,45,100)
print(a)

[ 15  19  25 -12  -6 -14  23  11   3  -3 -19 -11  18 -11   8  42 -16 -14
 -19 -28 -15  -7   7  26 -18  15 -16 -17  22  12  23  34  15  33  -7   7
  -9  31  26  16 -28  34  16  11  31  31  42  34  21   3  -1  -7  17  19
  25  -2 -21  40  17   1  -4 -23  35  12  32   2 -26 -20  -5  23  32  -7
  -6  34  30   5 -26 -11  19  20  29 -28  -3  41  24 -27  -9  37 -19  15
  37  14  26   3   5  -5  25 -24 -29  -4]


In [4]:
-9 in a

True

In [5]:
if -14 in a and not -6 in a:
    print("Something strange")
elif 45 in a:
    print("No 11")
else:
    print("Pues está el -14 y el -6, y no el 45")

Pues está el -14 y el -6, y no el 45


In [7]:
unique_a = np.unique(a)  # sort but
print(unique_a)
print(unique_a.size)

[-29 -28 -27 -26 -24 -23 -21 -20 -19 -18 -17 -16 -15 -14 -12 -11  -9  -7
  -6  -5  -4  -3  -2  -1   1   2   3   5   7   8  11  12  14  15  16  17
  18  19  20  21  22  23  24  25  26  29  30  31  32  33  34  35  37  40
  41  42]
56


In [9]:
unique_a, freq_a = np.unique(a,return_counts=True)
print(a)
print(len(a))
print("-"*10)
print(freq_a)
print(len(freq_a))
print("-"*10)
print(unique_a)
print(len(unique_a))
# ¿Cuántos elementos repetidos hay?

[ 15  19  25 -12  -6 -14  23  11   3  -3 -19 -11  18 -11   8  42 -16 -14
 -19 -28 -15  -7   7  26 -18  15 -16 -17  22  12  23  34  15  33  -7   7
  -9  31  26  16 -28  34  16  11  31  31  42  34  21   3  -1  -7  17  19
  25  -2 -21  40  17   1  -4 -23  35  12  32   2 -26 -20  -5  23  32  -7
  -6  34  30   5 -26 -11  19  20  29 -28  -3  41  24 -27  -9  37 -19  15
  37  14  26   3   5  -5  25 -24 -29  -4]
100
----------
[1 3 1 2 1 1 1 1 3 1 1 2 1 2 1 3 2 4 2 2 2 2 1 1 1 1 3 2 2 1 2 2 1 4 2 2 1
 3 1 1 1 3 1 3 3 1 1 3 2 1 4 1 2 1 1 2]
56
----------
[-29 -28 -27 -26 -24 -23 -21 -20 -19 -18 -17 -16 -15 -14 -12 -11  -9  -7
  -6  -5  -4  -3  -2  -1   1   2   3   5   7   8  11  12  14  15  16  17
  18  19  20  21  22  23  24  25  26  29  30  31  32  33  34  35  37  40
  41  42]
56


In [10]:
unique_a,index_a,freq_a = np.unique(a,return_counts=True,return_index=True)
print(freq_a)
print(index_a)
print("-"*10)
print(np.where(freq_a==4))
print(unique_a[17]) # se repite cuatro veces
print(unique_a[33]) # se repite cuatro veces
print(unique_a[50]) # se repite cuatro veces

print(a[np.where(a==-7)])

[1 3 1 2 1 1 1 1 3 1 1 2 1 2 1 3 2 4 2 2 2 2 1 1 1 1 3 2 2 1 2 2 1 4 2 2 1
 3 1 1 1 3 1 3 3 1 1 3 2 1 4 1 2 1 1 2]
[98 19 85 66 97 61 56 67 10 24 27 16 20  5  3 11 36 21  4 68 60  9 55 50
 59 65  8 75 22 14  7 29 91  0 39 52 12  1 79 48 28  6 84  2 23 80 74 37
 64 33 31 62 87 57 83 15]
----------
(array([17, 33, 50]),)
-7
15
34
[-7 -7 -7 -7]


In [12]:
np.sort(freq_a)[::-1]

array([4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.sort(freq_a)

print(np.array([0,4,1,2,5,7,9])[::-1])
print(np.argsort(np.array([0,4,1,2,5,7,9])))
print(np.argsort(np.array([0,4,1,2,5,7,9]))[::-1])

print("-"*10)

index_sorted = np.argsort(freq_a)[::-1] #https://numpy.org/doc/stable/reference/generated/numpy.argsort.html
print(index_sorted)

[9 7 5 2 1 4 0]
[0 2 3 1 4 5 6]
[6 5 4 1 3 2 0]
----------
[50 33 17 43 44 37 47 41 15  8 26  1 52 48 34 18 31 28 27 35  3 21 16 55
 13 19 20 30 11 39 38 36 53 54 51 49 45 46 42 40 32 22 25 24 29 23 12 14
  9 10  7  6  4  5  2  0]


In [15]:
a = np.arange(10)
b = np.arange(5,15)
print(a)
print(b)
print("-"*10)
print(np.in1d(a,b))
print(np.intersect1d(a,b))
print("-"*10)
print(np.setdiff1d(a,b))
print(np.setdiff1d(b,a))
print("-"*10)
print(np.union1d(a,b))

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
----------
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]
----------
[0 1 2 3 4]
[10 11 12 13 14]
----------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


C:\Users\Nico\AppData\Local\Temp\ipykernel_12324\1680166640.py:6: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a,b))


In [37]:
x = np.array([0, 0,2, 2, 3, 4, 54, 6, 7, 80, 9])
print(np.diff(x))
print(np.sign(np.diff(x)))
print(np.argwhere (np.sign(np.diff(x))==-1))# en que posiciones esta el menos 1
print(x[1:][np.argwhere (np.sign(np.diff(x))==-1)-1])

[  0   2   0   1   1  50 -48   1  73 -71]
[ 0  1  0  1  1  1 -1  1  1 -1]
[[6]
 [9]]
[[54]
 [80]]


In [40]:
sudoku = np.array([[5,3,0,0,7,0,0,0,0],
                 [6,0,0,1,9,5,0,0,0],
                 [1,9,8,0,0,0,0,6,0],
                 [8,0,0,0,6,0,0,0,3],
                 [4,0,0,8,0,3,0,0,1],
                 [7,0,0,0,2,0,0,0,6],
                 [0,6,0,0,0,0,2,8,0],
                 [3,8,0,4,1,9,7,2,5],
                 [4,0,0,0,8,0,0,7,9]])

print(sudoku[:0][np.argwhere (np.sign(np.diff(sudoku))==0) 0])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2952831778.py, line 11)